### PR TITLE
Replace AtomicLong to long while ReentrantReadWriteLock is enough

### PR DESCRIPTION
**Pull request by pifuant**

### CODE REVIEW

**Comment by pifuant** [comment]
@killme2008  @fengjiachun  PTAL

**Comment by fengjiachun** [comment]
I think you are right, 'lastCommittedIndex' does not need to be AtomicLong, ReentrantReadWriteLock is enough, but I think, can you optimize it further?
replace ReentrantReadWriteLock with StampedLock, then getLastCommittedIndex() uses StampedLock#tryOptimisticRead() to read.

@killme2008 @pifuant PTAL

**Comment by killme2008** [comment]
Good catch!  Yep, AtomicLong is not necessary here, it can be replaced by primitive `long` type.

I agree with @fengjiachun , use `StampedLock` is a better choice because `getLastCommittedIndex` is called so frequently that `tryOptimisticRead` will help.

**Comment by fengjiachun** [comment]
@pifuant 

```
public long getLastCommittedIndex() {
        long stamp = stampedLock.tryOptimisticRead();
        long optimisticVal = this.lastCommittedIndex;
        if (stampedLock.validate(stamp)) {
            return optimisticVal;
        }
        stamp = stampedLock.readLock();
        try {
            return this.lastCommittedIndex;
        } finally {
            stampedLock.unlockRead(stamp);
        }
    }
```

**Comment by pifuant** [comment]
@killme2008 @fengjiachun PTAL

**Comment by fengjiachun** [comment]
@pifuant 
1. `long stamp -> final long stamp` ? except on tryOptimisticRead()
2.  `stampedLock.unlock() -> stampedLock.unlockWrite()/stampedLock.unlockRead()` ？

**Comment by pifuant** [comment]
@fengjiachun PTAL

**Comment by fengjiachun** [comment]
@pifuant tks

**Pull request merged**
